name: 'Process SSH Connection'
description: 'Process SSH connection details based on tag or branch'
branding:
  icon: 'terminal'
  color: 'green'

inputs:
  suffix:
    description: 'Direct suffix value to use (takes precedence over ref)'
    required: false
    default: ''
  ref:
    description: 'Reference string to process (defaults to github.ref)'
    required: false
    default: ${{ github.ref }}
  suffix_regex:
    description: 'Regular expression to extract suffix from ref'
    required: false
    default: 'refs/(tags|heads)/.*-(.+)'
  suffix_group:
    description: 'Group number in regex that contains the suffix'
    required: false
    default: '2'

outputs:
  ssh_host:
    description: 'Selected SSH host'
    value: ${{ steps.process.outputs.ssh_host }}
  ssh_username:
    description: 'Selected SSH username'
    value: ${{ steps.process.outputs.ssh_username }}
  ssh_port:
    description: 'Selected SSH port'
    value: ${{ steps.process.outputs.ssh_port }}
  environment:
    description: 'Selected environment'
    value: ${{ steps.process.outputs.environment }}
  environment_upper:
    description: 'Selected environment in uppercase'
    value: ${{ steps.process.outputs.environment_upper }}
  key:
    description: 'SSH key with processed line breaks'
    value: ${{ steps.ssh_key.outputs.key }}

runs:
  using: "composite"
  steps:
    - name: Process SSH connection
      id: process
      shell: bash
      run: |
        suffix="${{ inputs.suffix }}"
        ref="${{ inputs.ref }}"
        suffix_regex="${{ inputs.suffix_regex }}"
        suffix_group="${{ inputs.suffix_group }}"

        if [[ -n "$suffix" ]]; then
          # 如果直接提供了 suffix，使用它
          suffix_upper=$(echo "$suffix" | tr '[:lower:]' '[:upper:]')
        elif [[ "$ref" =~ $suffix_regex ]]; then
          # 如果没有直接提供 suffix，从 ref 中提取
          suffix="${BASH_REMATCH[$suffix_group]}"
          suffix_upper=$(echo "$suffix" | tr '[:lower:]' '[:upper:]')
        else
          echo "No suffix provided and no suffix found in ref: $ref using regex: $suffix_regex"
          exit 1
        fi

        # 构建变量名
        ssh_host="SSH_HOST_${suffix_upper}"
        ssh_username="SSH_USERNAME_${suffix_upper}"
        ssh_port="SSH_PORT_${suffix_upper}"
        ssh_key="SSH_KEY_${suffix_upper}"

        # 输出标准化的变量名
        echo "ssh_host=$ssh_host" >> $GITHUB_OUTPUT
        echo "ssh_username=$ssh_username" >> $GITHUB_OUTPUT
        echo "ssh_port=$ssh_port" >> $GITHUB_OUTPUT
        echo "environment=${suffix}" >> $GITHUB_OUTPUT
        echo "environment_upper=${suffix_upper}" >> $GITHUB_OUTPUT
        echo "ssh_key_name=$ssh_key" >> $GITHUB_OUTPUT

    - name: Process SSH key
      id: ssh_key
      shell: bash
      run: |
        echo "key<<EOF" >> $GITHUB_OUTPUT
        echo "${{ env[steps.process.outputs.ssh_key_name] }}" | sed 's/\\n/\n/g' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT